# Generated by Django 2.0.7 on 2018-11-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c',
            fields=[
                ('c_LID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('c_name', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='cars',
            fields=[
                ('c_plnumber', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='charger_scooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charged', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='chargers',
            fields=[
                ('c_LID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('c_name', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='in_usa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=128)),
                ('city_price', models.IntegerField(default=1)),
                ('State', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='out_usa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=128)),
                ('city_price', models.IntegerField(default=1)),
                ('Country_name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rented_scooters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scapp.c')),
            ],
        ),
        migrations.CreateModel(
            name='s',
            fields=[
                ('s_sid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('s_battery', models.IntegerField(default=0)),
                ('s_pla', models.IntegerField(default=0)),
                ('s_plo', models.IntegerField(default=0)),
                ('s_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scapp.in_usa')),
            ],
        ),
        migrations.AddField(
            model_name='rented_scooters',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scapp.s'),
        ),
        migrations.AddField(
            model_name='charger_scooter',
            name='charger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scapp.chargers'),
        ),
        migrations.AddField(
            model_name='charger_scooter',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scapp.s'),
        ),
        migrations.AddField(
            model_name='cars',
            name='charger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scapp.chargers'),
        ),
        migrations.AddField(
            model_name='c',
            name='c_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scapp.in_usa'),
        ),
    ]
