# Generated by Django 2.0.7 on 2018-11-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('city_price', models.IntegerField(default=1)),
                ('in_the_usa', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='out_usa',
        ),
        migrations.RemoveField(
            model_name='c',
            name='c_city',
        ),
        migrations.AlterField(
            model_name='s',
            name='s_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scapp.city'),
        ),
        migrations.DeleteModel(
            name='in_usa',
        ),
    ]
