# Generated by Django 2.0.7 on 2018-11-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scapp', '0002_auto_20181127_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_usa',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scapp.city')),
                ('State', models.CharField(max_length=128)),
            ],
            bases=('Scapp.city',),
        ),
        migrations.CreateModel(
            name='out_usa',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scapp.city')),
                ('Country_name', models.CharField(max_length=128)),
            ],
            bases=('Scapp.city',),
        ),
    ]
